project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2023 ITCOocean Hackweek"
  site-url: https://Hackweek-ITCOocean.github.io/2023-Hackbook
  repo-url: https://github.com/Hackweek-ITCOocean/2023-Hackbook
  repo-actions: [edit, issue, source]
  
  page-footer: "ITCOocean (2023). 2023 Hackweek" 
 
  sidebar:
    logo: images/incois-logos.png
    pinned: true
    align: center
    
    style: "docked"
    search: true
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        contents:
          - text: "Overview"
            href: index.md
          - team.md
          - schedule.md
          - setup.md
          - support.md
          - participants.md
      - section: "Daily Schedule"
        contents:
          - section: "01 Monday"
            contents:
              - text: L Indian Ocean
              - text: L Remote-sensing data
              - text: H GitHub 1
                href: content/01-github.md
              - text: L Geoscience cloud tools
                href: content/01-intro-to-cloud-geoscience.qmd
              - text: H Jupyter hubs
                href: content/01-intro-to-jupyterhub.qmd
          - section: "01 Tuesday"
            contents:
              - text: L Online RS data
              - text: L EarthData and Copernicus
              - text: H RStudio
                href: content/02-rstudio.md
              - text: H GitHub 2
                href: content/02-github-2.md
              - text: H Quarto
          - section: "01 Wednesday"
            contents:
              - text: L Climate change
              - text: L IndOBIS
              - text: H Programming with AI
                href: content/02-rstudio.md
              - text: H Git
                href: content/03-git-rstudio.md
              - text: H Loading data in R
          - section: "01 Thursday"
            contents:
              - text: L SDMs
              - text: L SDM examples
              - text: L Statistics 1
              - text: H Lab Setup
                href: r-notebooks/Lab-setup.qmd
              - text: H Geospatial Lab 1
                href: r-notebooks/geospatial-lab1.qmd
          - section: "01 Friday"
            contents:
              - text: L How to sprint
              - text: L Statistics 2
              - text: H Geospatial Lab 2
      - section: "Python Tutorials"
        contents:
          - section: "Data Access"
            contents:
              - python-notebooks/00_NASA_Earthdata_Authentication.ipynb
              - python-notebooks/01_earthaccess_Downloader.ipynb
              - python-notebooks/01_ERA5_S3_Downloader.ipynb
              - python-notebooks/01_ERDDAP_Downloader.ipynb
              - python-notebooks/01_MOTU_Downloader.ipynb
          - section: "Using Data"
            contents:
              - python-notebooks/02_Using_Data.ipynb
              - python-notebooks/02_Graphing_Data.ipynb
              - python-notebooks/02_Zarr_Access_netCDF.ipynb
              - python-notebooks/02_Xarray_hvplot.ipynb
              - python-notebooks/02_Xarray_hvplot.ipynb              
          - section: "Machine Learning"
            contents:
          - section: "Applications"
            contents:
          - section: "IO Zarr Database"
            contents:
              - python-notebooks/04_Combining_Data.ipynb
              - python-notebooks/04_Appending_Data.ipynb
      - section: "Projects"
        contents:
          - projects/index.md
          - projects/hackathon-projects.md
      - section: "Further Resources"
        contents:
          - content/XX-r-and-python-resources.md
          - content/XX-further-resources.md
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://itcoocean.2i2c.cloud/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/orgs/Hackweek-ITCOocean/discussions
        text: "Discussions"
      - icon: globe
        href: https://github.com/Hackweek-ITCOocean
        text: "GitHub org"
      - icon: github
        href: https://github.com/Hackweek-ITCOocean/2023-Hackbook
        text: "Hackbook repo"

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2

filters:
  - include-files.lua
  - quarto
