project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2023 ITCOocean Hackweek"
  site-url: https://Hackweek-ITCOocean.github.io/2023-Cloudbook
  
  repo-url: https://github.com/Hackweek-ITCOocean/2023-Cloudbook
  repo-actions: [edit, issue]
  
  page-footer: "ITCOocean (2023). 2023 Hackweek" 
 
  sidebar:
    logo: assets/images/incois-logos.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://Hackweek-ITCOocean.github.io
        text: "Hackweek ITCOocean"
      - icon: github
        href: https://github.com/Hackweek-ITCOocean/2023-Cloudbook
        text: "2023 Hackweek Tutorials"
    
    style: "docked"
    search: true
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        contents:
          - index.md
          - team.md
      - section: "Logistics"
        contents:
          - logistics/index.md
          - logistics/schedule.md
      - section: "Week 1"
        contents:
          - week1-tutorials/01-AM-intro-to-regional-data.md
          - week1-tutorials/01-PM-software.md
          - week1-tutorials/02-AM-online-databases.md
          - week1-tutorials/02-PM-git-and-github.md
          - week1-tutorials/03-AM-raster-and-nc-in-R.md
          - week1-tutorials/03-PM-spatial-maps-in-R.md
          - week1-tutorials/04-AM-spatial-maps-in-R.md
          - week1-tutorials/04-PM-intro-to-sdms.md
          - week1-tutorials/05-AM-guest-lectures.md
          - week1-tutorials/05-PM-project-brainstorming.md
      - section: "Week 2"
        contents: 
          - week2-tutorials/01-AM-preparing-data.md
          - week2-tutorials/01-PM-project-pitches.md
          - week2-tutorials/02-AM-sdm-part1.md
          - week2-tutorials/03-AM-sdm-part2.md
          - week2-tutorials/04-AM-guest-lectures.md
          - week2-tutorials/05-PM-project-presentations.md
      - section: "Python Tutorials"
        contents:
          - section: "Data Access"
            contents:
              - Python-notebooks/00_NASA_Earthdata_Authentication.ipynb
              - Python-notebooks/01_earthaccess_Downloader.ipynb
              - Python-notebooks/01_ERA5_S3_Downloader.ipynb
              - Python-notebooks/01_ERDDAP_Downloader.ipynb
              - Python-notebooks/01_MOTU_Downloader.ipynb
              - Python-notebooks/01_Combining_Data.ipynb
      - section: "Projects"
        contents:
          - projects/index.md
          - projects/hackathon-projects.md
      - section: "Further Resources"
        contents:
          - further-resources.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2

filters:
  - include-files.lua
  - quarto
