project:
  type: site
  output-dir: _site

execute:
  freeze: true

site:
  site-url: https://nasa-openscapes.github.io/2021-Cloud-Hackathon
  repo-url: https://github.com/nasa-openscapes/2021-Cloud-Hackathon
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    title: "2021 Cloud Hackathon"
    logo: https://user-images.githubusercontent.com/2915555/133525653-2a2278b1-1015-4350-b2a5-160d125aaaf7.png
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/2021-Cloud-Hackathon
    contents:
      - text: "Welcome"
        href: index.md
      - section: logistics/index.md
        contents:
          - logistics/schedule.md
          - logistics/prerequisites.md
          - logistics/getting-help.md
      - section: clinic/index.md
        contents:
          - clinic/jupyterhub.md
          - clinic/notebooks.md
          - clinic/github.md
          - clinic/earthdata.md
      - section: tutorials/index.md
        contents: 
          - tutorials/getting-set-up.md  ## tutorial 0
          - tutorials/Data_discovery_with_cmr.ipynb ## tutorial 1
          - tutorials/Data_Discovery__CMR-STAC_API.ipynb ## tutorial 2
          - tutorials/Introduction_to_xarray.ipynb ## tutorial 3
          - tutorials/NASA_Earthdata_Authentication.ipynb ## tutorial 4
          - tutorials/Data_Access__Direct_S3_Access.ipynb ## tutorial 5
          - tutorials/Data_Access__Direct_S3_Access__PODAAC_ECCO_SSH.ipynb
          - tutorials/Data_Access__Harmonize-cloud-non-cloud.ipynb ## tutorial 7
          - tutorials/Data_Access__Harmony_Subsetting.ipynb ## tutorial 8
          - tutorials/Zarr_Access.ipynb ## tutorial 9
      - section: tutorials-templates/index.md
      - section: projects/index.md
        contents:
          - projects/workflow.md
          - projects/hackathon-projects.md
      - section: "Additional Resources"
        contents:
          - tutorials/Additional_Resources__Direct_S3_Access__gdalvrt.ipynb
          - tutorials/Additional_Resources__Direct_S3_Access__rioxarray_clipping.ipynb
          
  footer: "PODAAC, NSIDC DAAC and LPDAAC (2021). 2021 Cloud Hackathon"

filters:
  - include-files.lua
  
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
