project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"

execute:
  freeze: true
  
website:
  page-navigation: true  
  title: "2023 ITCOocean Hackweek"
  site-url: https://Hackweek-ITCOocean.github.io/2023-Hackbook
  
  repo-url: https://github.com/Hackweek-ITCOocean/2023-Hackbook
  repo-actions: [edit, issue]
  
  page-footer: "ITCOocean (2023). 2023 Hackweek" 
 
  sidebar:
    logo: assets/images/incois-logos.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://Hackweek-ITCOocean.github.io
        text: "Hackweek ITCOocean"
      - icon: github
        href: https://github.com/Hackweek-ITCOocean/2023-Hackbook
        text: "2023 Hackweek Tutorials"
    
    style: "docked"
    search: true
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        contents:
          - text: "Overview"
            href: index.md
          - team.md
          - schedule.md
          - support.md
      - section: "Cloud Tools"
        contents:
          - setup/index.md
          - text: JupyterHub
            href: setup/jupyterhub.md
          - text: R - RStudio
            href: setup/rstudio.md
          - text: Python - Jupyter Notebooks
            href: setup/jupyter-notebooks.md
          - setup/git.md
          - setup/earthdata.md
          - setup/data.md
      - section: "Week 1"
        contents:
          - week1-tutorials/01-AM-preparing-data.md
          - week1-tutorials/01-PM-project-pitches.md
          - week1-tutorials/02-AM-sdm-part1.md
          - week1-tutorials/03-AM-sdm-part2.md
          - week1-tutorials/04-AM-guest-lectures.md
          - week1-tutorials/05-PM-project-presentations.md
      - section: "Week 2 Lectures"
        contents: 
          - week2-tutorials/01-AM-preparing-data.md
          - week2-tutorials/01-PM-project-pitches.md
          - week2-tutorials/02-AM-sdm-part1.md
          - week2-tutorials/03-AM-sdm-part2.md
          - week2-tutorials/04-AM-guest-lectures.md
          - week2-tutorials/05-PM-project-presentations.md
      - section: "R Tutorials"
        contents:
          - r-notebooks/Lab-setup.qmd
          - r-notebooks/geospatial-lab1.qmd
          - r-notebooks/SDM-lab1.qmd
      - section: "Python Tutorials"
        contents:
          - section: "Data Access"
            contents:
              - python-notebooks/00_NASA_Earthdata_Authentication.ipynb
              - python-notebooks/01_earthaccess_Downloader.ipynb
              - python-notebooks/01_ERA5_S3_Downloader.ipynb
              - python-notebooks/01_ERDDAP_Downloader.ipynb
              - python-notebooks/01_MOTU_Downloader.ipynb
          - section: "Using Data"
            contents:
              - python-notebooks/02_Using_Data.ipynb
              - python-notebooks/02_Graphing_Data.ipynb
              - python-notebooks/02_Zarr_Access_netCDF.ipynb
              - python-notebooks/02_Xarray_hvplot.ipynb
              - python-notebooks/02_Xarray_hvplot.ipynb              
          - section: "Machine Learning"
            contents:
          - section: "Applications"
            contents:
          - section: "IO Zarr Database"
            contents:
              - python-notebooks/04_Combining_Data.ipynb
              - python-notebooks/04_Appending_Data.ipynb
      - section: "Projects"
        contents:
          - projects/index.md
          - projects/hackathon-projects.md
      - section: "Further Resources"
        contents:
          - further-resources.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2

filters:
  - include-files.lua
  - quarto
