project:
  type: site
  output-dir: _site

execute:
  freeze: true

site:
  site-url: https://nasa-openscapes.github.io/2021-Cloud-Hackathon
  repo-url: https://github.com/nasa-openscapes/2021-Cloud-Hackathon
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    title: "2021 Cloud Hackathon"
    logo: nasa-openscapes.png
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/2021-Cloud-Hackathon
    contents:
      - text: "Welcome"
        href: index.md
      - section: overview/index.md
        contents:
          - overview/about.md
          - overview/code-of-conduct.md
      - section: logistics/index.md
        contents:
          - logistics/logistics-overview.md
          - section: logistics/schedule.md
            contents:
              - logistics/carpentries.md
              - logistics/hackathon.md
          - logistics/getting-help.md
          - logistics/coffee-breaks.md
      - section: preparation/index.md
        contents:
          - preparation/shell-for-github.md
          - preparation/python.md
          - preparation/jupyterhub.md
      - section: tutorials/index.md
        contents: 
          - tutorials/getting-started.md
          - tutorials/Data_Discovery__CMR-STAC_API.ipynb
      - section: projects/index.md
        contents:
          - projects/project-overview.md
          - projects/hacking.md
          - projects/hackathon-projects.md

  footer: "NASA Openscapes Team (2021). 2021 Cloud Hackathon"

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
